--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Rushil13579/AdminTrollV2
build-by-default: true
branches:
- main
projects:
  AdminTrollV2:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
...
