name: AdminTrollV2
main: Rushil13579\AdminTrollV2\Main
api: 3.0.0
version: 1.0.0
author: Rushil13579

commands:
    trollhelp:
        description: Help regarding AdminTrollV2!
    fakerestart:
        description: FakeRestart Troll!
    fakeop:
        description: FakeOp Troll!
    fakedeop:
        description: FakeDeop Troll!
    pumpkinhead:
        description: PumpkinHead Troll!
    launch:
        description: Launch Troll!
    push:
        description: Push Troll!
    spam:
        description: Spam Troll!
    crash:
        description: Crash Troll!
    badapple:
        description: BadApple Troll!
    boom:
        description: Boom Troll!
    switch:
        description: Switch Troll!
    potatoinc:
        description: PotatoInv Troll!
    turn:
        description: Turn Troll!
    alone:
        description: Alone Troll!
    clumsy:
        description: Clumsy Troll!
    dropinv:
        description: DropInv Troll!
    shuffle:
        description: Shuffle Troll!
    drunk:
        description: Drunk Troll!
    void:
        description: Void Troll!
    chat:
        description: Chat Troll!
    burn:
        description: Burn Troll!
    hurt:
        description: Hurt Troll!
    starve:
        description: Starve Troll!
    nomine:
        description: NoMine Troll!
    noplace:
        description: NoPlace Troll!
    trap:
        description: Trap Troll!