name: AdminTrollV2
main: Rushil13579\AdminTrollV2\Main
api: 3.0.0
version: 1.0.0
mcpe-protocol: [431]
author: Rushil13579

commands:
    trollhelp:
        description: List of trolls and thier usages
    fakerestart:
        description: Awww.. the server is restarting, OR IS IT?
    fakeop:
        description: Sends a op message to the victim. They are not opped...
    fakedeop:
        description: Sends a deop message to the victim. They are not deopped...
    pumpkinhead:
        description: Gotta hide from the endermen (undoable)
    launch:
        description: 3... 2... 1... liftoff!
    push:
        description: An uncontrolled flight
    spam:
        description: Spams the victim's chat in enchantment table language... see if you can decipher it
    crash:
        description: Kicks the play with a not so nice disconnected message
    badapple:
        description: The doctor says, never eat an apple if it has gone bad... what if you still do?
    boom:
        description: Blow up your enemies!
    swap:
        description: Swap positions with your victim
    potatoinc:
        description: Fills the victim's inventory with potatoes (undoable)
    turn:
        description: Turn the victim 180 degrees
    alone:
        description: Hides every player for the victim (toggleable)
    clumsy:
        description: Carefull! The victim might just drop something
    dropinv:
        description: The victim fell and dropped his inventory (undoable)
    shuffle:
        description: Ugh! I dont even know what is where now... (undoable)
    drunk:
        description: Drank too much... feeling nauseous
    void:
        description: Journey to the center of the Earth, or in this case the void...
    haunt:
        description: Spooky sounds O_O!
    fakeban:
        description: Are you sure you got banned?
    garble:
        description: The victim's messages will stop making sense (toggleable)
    chat:
        description: Sends a chat message or run a command on behalf of the victim
    burn:
        description: BURN!!
    hurt:
        description: Ouch! That hurts...
    starve:
        description: The victim's metabolism must be really fast
    nomine:
        description: Oh cant mine? Probably lag...
    noplace:
        description: Oh cant place? Probably lag...
    trap:
        description: The victim does not deserve to be free

permissions:
    admintrollv2.all:
        description: Master permission for AdminTrollV2!